
services:
  dotapredict-api:
    container_name: dotapredict-api
    build: .
    ports:
      - "8000:8000"
    environment:
      - DOTAPREDICT_USER=postgres
      - DOTAPREDICT_PASSWORD=postgres
      - DOTAPREDICT_DB=postgres
      - DOTAPREDICT_HOST=db
      - DOTAPREDICT_PORT=5432
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: matchapp_job
    depends_on:
      - dotapredict-api
      - redis
    env_file:
      - .env

volumes:
  pgdata: {}