
services:
  djangoapp:
    container_name: userapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - DOTAPREDICT_USER=postgres
      - DOTAPREDICT_PASSWORD=postgres
      - DOTAPREDICT_DB=postgres
      - DOTAPREDICT_HOST=db
      - DOTAPREDICT_PORT=5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}