# Generated by Django 3.2.5 on 2025-06-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
