/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DraftBar: typeof import('./src/components/DraftBar.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HeroBan: typeof import('./src/components/HeroBan.vue')['default']
    HeroPick: typeof import('./src/components/HeroPick.vue')['default']
    HeroSelection: typeof import('./src/components/HeroSelection.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Menu: typeof import('./src/components/menuComponent/Menu.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
